# Generated by Django 5.2.12 on 2026-05-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_vpa', models.CharField(blank=True, help_text='e.g. greenwood@razorpay', max_length=100, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_from', models.CharField(blank=True, help_text='e.g. whatsapp:+14155238886', max_length=50, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=50, null=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fee_reminder_days', models.JSONField(default=list, help_text='Days before due date to send reminders e.g. [7, 3, 1]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
        ),
    ]
